baseURL: http://lance.sda1.net/
languageCode: ja-jp
title: LanceLight
theme: hextra
enableRobotsTXT: true
enableGitInfo: true
# enableEmoji: false
hasCJKLanguage: true

defaultContentLanguage: ja-jp
languages:
  en:
    languageName: English
    weight: 2
    title: LanceLight
  ja-jp:
    languageName: 日本語
    languageCode: ja-JP
    weight: 1
    title: LanceLight

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

enableInlineShortcodes: true

menu:
  main:
    - identifier: documentation
      name: Documentation
      pageRef: /docs
      weight: 1
    - name: Search
      weight: 5
      params:
        type: search
    - name: GitHub
      weight: 6
      url: "https://github.com/nexryai/lance-light"
      params:
        icon: github

  sidebar:
    - identifier: more
      name: More
      params:
        type: separator
      weight: 1
    - identifier: about
      name: "Home"
      pageRef: "/"
      weight: 2

params:
  description: Simple and powerful, Modern firewall for Linux

  navbar:
    displayTitle: true
    displayLogo: true
    logo:
      path: images/logo.svg
      dark: images/logo-dark.svg
      # width: 40
      # height: 20
      # link: /
    width: wide

  page:
    # full (100%), wide (90rem), normal (1280px)
    width: normal

  theme:
    # light | dark | system
    default: system
    displayToggle: true

  footer:
    enable: true
    displayCopyright: true
    displayPoweredBy: true
    width: normal

  displayUpdatedDate: true
  dateFormat: "January 2, 2006"

  # Search
  # flexsearch is enabled by default
  search:
    enable: true
    type: flexsearch

    flexsearch:
      # index page by: content | summary | heading | title
      index: content


